### ISSUE TITLE
Cannot set up using Llama-2

### ISSUE THREAD

**Issue by yoshinorisano** [shansongliu/M2UGen#5]
First of all, thank you for making your great research results open source!

I want to reproduce the research results, but there are some setup issue using Llama-2.

Here it refers to `params.json`, but it is not included in Llama-2.
https://github.com/shansongliu/M2UGen/blob/974f5c78a49b7ab2cb5c83b2d9d684ec3dc69140/M2UGen/llama/m2ugen.py#L131

https://huggingface.co/meta-llama/Llama-2-7b-hf/tree/main

It seems that the code is based on the original Llama (not Llama-2).
Could you please improve it so that it works with Llama-2?

**Comment by shansongliu** [comment]
> First of all, thank you for making your great research results open source!
> 
> I want to reproduce the research results, but there are some setup issue using Llama-2.
> 
> Here it refers to `params.json`, but it is not included in Llama-2.
> 
> https://github.com/shansongliu/M2UGen/blob/974f5c78a49b7ab2cb5c83b2d9d684ec3dc69140/M2UGen/llama/m2ugen.py#L131
> 
> https://huggingface.co/meta-llama/Llama-2-7b-hf/tree/main
> 
> It seems that the code is based on the original Llama (not Llama-2). Could you please improve it so that it works with Llama-2?

Greetings and thanks for your interest in our project! Our model is indeed based on LLaMA 2, @crypto-code can you take a look at this?

**Comment by crypto-code** [comment]
> First of all, thank you for making your great research results open source!
> 
> I want to reproduce the research results, but there are some setup issue using Llama-2.
> 
> Here it refers to `params.json`, but it is not included in Llama-2.
> 
> https://github.com/shansongliu/M2UGen/blob/974f5c78a49b7ab2cb5c83b2d9d684ec3dc69140/M2UGen/llama/m2ugen.py#L131
> 
> https://huggingface.co/meta-llama/Llama-2-7b-hf/tree/main
> 
> It seems that the code is based on the original Llama (not Llama-2). Could you please improve it so that it works with Llama-2?

To allow for modification of parts of the LLaMA-2 model, such as the addition of multi-modal inputs across the different layers, we utilize the original checkpoints from LLaMA-2 instead of the HuggingFace checkpoints. The original LLaMA-2 checkpoints are provided by Meta and the instructions for obtaining them are given [here](https://github.com/facebookresearch/llama/blob/main/README.md). 

I hope this answers your question, do let us know if there are any issue here.

**Comment by yoshinorisano** [comment]
Thank you!
I have successfully obtained the original checkpoint.
